### ISSUE TITLE
Unhelpful stacktrace when you return something other than a Thenable

### ISSUE THREAD

**Issue by meticoeus** [ef-labs/when.java#6]
Not supporting returning a value from a promise method violates the A+ spec and leads to a lot of return when.resolve(x) boilerplate.

When you forget to do this somewhere the stack trace gives no indication where you forgot the boilerplate:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.englishtown.promises.Thenable
        at com.englishtown.promises.internal.PromiseHelper.tryCatchReject(PromiseHelper.java:156)
        at com.englishtown.promises.internal.handlers.FulfilledHandler.when(FulfilledHandler.java:36)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.englishtown.promises.internal.handlers.DeferredHandler.run(DeferredHandler.java:84)
        at com.englishtown.promises.impl.DefaultScheduler.drain(DefaultScheduler.java:63)
        at com.englishtown.vertx.promises.impl.VertxExecutor.lambda$execute$28(VertxExecutor.java:25)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Unknown Source)
```

Ideally, this library would adopt the A+ spec, supporting any return value, checking whether it is an instance of Thenable, and handling it accordingly.

Otherwise, is it possible to get a more informative stack trace?

We are using this project is a Groovy project in Vertx 3 so the expectation is essentially identical to JavaScript behavior.

**Comment by adrianluisgonzalez** [comment]
Fair points, adding a commit that should resolve this.  Let me know if this works for you and I can cut a release.

**Comment by meticoeus** [comment]
Its working. This should make working with promises much more natural, mirroring our client code.

**Comment by adrianluisgonzalez** [comment]
Released when.java 3.1.1
